# dependencies
markdown: rdiscount
pygments: true

# links
permalink: /:categories/:title

# setup
title: "root@infoslack:~#"
destination: ./_site
baseurl: "/"
paginate: 10
exclude: [README.md, config, vendor, Gemfile, Gemfile.lock]

# vars
workshops: http://infoslack.com/workshops/
rubyconf: http://infoslack.com/rubyconf/
twitter: https://twitter.com/infoslack
github: https://github.com/infoslack
linkedin: https://www.linkedin.com/in/infoslack
feed: http://infoslack.com/atom.xml
