name: "root@infoslack:~#"
markdown: rdiscount
permalink: /:categories/:title
pygments: true
destination: ./_deploy
exclude: [README.md, Capfile, config]
jekyll-press:
  css_options: {}
  html_options: {}
