# dependencies
markdown: kramdown
highlighter: rouge
plugins: [jekyll-gist]

# links
permalink: /:categories/:title

# setup
title: "root@infoslack:~#"
destination: ./_site
url: "https://infoslack.com"
baseurl: ""
exclude: [README.md, Dockerfile, docker-compose.yml, Gemfile, Gemfile.lock, .dockerignore, .gitignore]

disqus_shortname: infoslack

# vars
workshops: https://infoslack.com/workshops/
rubyconf: https://infoslack.com/rubyconf2015/docker/
twitter: https://twitter.com/infoslack
github: https://github.com/infoslack
linkedin: https://www.linkedin.com/in/infoslack
feed: https://infoslack.com/atom.xml
