version: "3"
services:
  blog:
    image: infoslack/blog
    container_name: blog
    volumes:
      - /home/infoslack/data/ssl/caddy:/root/.caddy
      - /home/infoslack/data/cv:/cv
      - /home/infoslack/data/ansible:/blog/ansible
      - /home/infoslack/data/docker:/blog/docker
      - /home/infoslack/data/unikernels:/blog/unikernels
      - /home/infoslack/data/metasploit:/blog/metasploit
      - /home/infoslack/data/rubyconf2015:/blog/rubyconf2015
      - /home/infoslack/data/workshops:/blog/workshops
    ports:
      - "80:80"
      - "443:443"
    command: /usr/bin/caddy run -config /etc/Caddyfile
