version: '3.6'
services:
  blog:
    build: .
    container_name: blog
    volumes:
      - /data/ssl/caddy:/root/.caddy
      - /data/cv:/cv
      - /data/ansible:/blog/ansible
      - /data/docker:/blog/docker
      - /data/unikernels:/blog/unikernels
      - /data/metasploit:/blog/metasploit
      - /data/rubyconf2015:/blog/rubyconf2015
      - /data/workshops:/blog/workshops
    ports:
      - "80:80"
      - "443:443"
    command: /usr/bin/caddy --conf /etc/Caddyfile --log stdout
